---
title: "Examining eQTL and module QTLs"
author: Anna L Tyler
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    code_folding: hide
    collapsed: no
    toc: yes
    toc_float: yes
---

```{r set_type}
is.interactive = FALSE
#is.interactive = TRUE

args <- commandArgs(trailingOnly=T)
tissue.type <- args[1]

if(is.na(tissue.type)){
  tissue.type = "Adipose"
  clust.type = "WGCNA_Clusters"
}
```

The purpose of this workflow is to further analyze the expression
modules generated by 1.Cluster_Transcripts.Rmd. We will look at 
local and distal eQTL as they relate to module QTLs


```{r load_code}
library("here")
all.fun <- list.files(here("Code"), full.names = TRUE, pattern = ".R")
for(i in 1:length(all.fun)){source(all.fun[i])}
```

```{r load_libraries, message = FALSE, warning = FALSE, error = FALSE}
all.packages <- c("pheatmap", "qtl2", "gprofiler2", "cape", "CoExpNets", "abind")
load_libraries(all.packages)
```


```{r read_data}
all.var <- ls()
data.loaded <- as.logical(length(which(all.var == "dataset.DO.Cube.SkeletalMuscle")))
if(!data.loaded){
  expr.data <- readRDS(here("Data", "RDS_datasets_tissues", paste0(tissue.type, ".RDS")))
  genotype.data <- load(here("Data", "dataset.DO.CUBE.multissue.RData"))
  me <- readRDS(here("Results", clust.type, tissue.type, "Module_Eigengenes.RDS"))
  mod.mem <- readRDS(here("Results", clust.type, tissue.type, "Module_Membership.RDS"))
  eqtl <- as.matrix(expr.data$lod.peaks$additive)
  eqtl.info <- as.matrix(expr.data$annot.mrna)
  }

eqtl.split.pos <- strsplit(eqtl[,"marker.id"], "_")
eqtl.pos <- sapply(eqtl.split.pos, function(x) as.numeric(x[2]))/1e6
eqtl.chr <- sapply(eqtl.split.pos, function(x) x[1])
```


```{r}
mb.buffer = 4
mod = "9"
mod.locale <- which(names(mod.mem) == mod)

mod.genes <- mod.mem[[mod.locale]]

#scan ME
mod.scan <- scan1(genoprobs, me[,mod.locale,drop=FALSE])
quartz();plot(mod.scan, map = map)
#find peaks
peak.table <- as.matrix(find_peaks(mod.scan, map = map, threshold = 6))

peak.idx <- 3

peak.chr <- peak.table[peak.idx,"chr"]
peak.pos <- as.numeric(peak.table[peak.idx,"pos"])

chr.eqtl <- which(eqtl.chr == chr)
eqtl.pos.overlap <- intersect(which(eqtl.pos >= (peak.pos - mb.buffer)), which(eqtl.pos <= (peak.pos + mb.buffer)))
eqtl.overlap <- intersect(chr.eqtl, eqtl.pos.overlap)
overlapping.eqtl <- eqtl[eqtl.overlap,]

module.overlapping.eqtl <- overlapping.eqtl[which(overlapping.eqtl[,1] %in% mod.genes),]


mod.gene.info <- eqtl.info[match(module.overlapping.eqtl[,1], eqtl.info[,1]),]

mod.gene.info[chr.locale,c("gene.id", "chr", "start", "end")]

```



